name: Google Trends Data Pipeline

on:
  schedule:
    - cron: '0 0 * * 1,4-6'  # Ejecuta el trabajo todos los días a medianoche UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Puedes especificar la versión de Python que necesites

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Google Trends Script
        env:
          GOOGLE_SHEETS_CREDS_BASE64: ${{ secrets.GOOGLE_SHEETS_CREDS_BASE64 }}
          SPREADSHEET_ID_TRENDS: ${{ secrets.SPREADSHEET_ID_TRENDS }}
          SPREADSHEET_ID_KEYWORDS: ${{ secrets.SPREADSHEET_ID_KEYWORDS }}
          SECRET_FOLDER_ID: ${{ secrets.SECRET_FOLDER_ID }}
          SECRET_FOLDER_ID_DF: ${{ secrets.SECRET_FOLDER_ID_DF }}
          SPREADSHEET_ID_KW: ${{ secrets.SPREADSHEET_ID_KW }}
          SECRET_CREDS_FILE: ${{ secrets.SECRET_CREDS_FILE }}
        run: |
          python google_trends_data.py
